name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - '**/FASTDEV**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      IS_FASTDEV: ${{ contains(github.ref, 'FASTDEV') }}

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Bun
      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV
          echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV
        shell: bash

      # Cache Bun dependencies
      - name: Bun Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Install dependencies
      - name: Install dependencies
        run: ~/.bun/bin/bun install
        shell: bash
        env:
          BUN_INSTALL: ${{ env.BUN_INSTALL }}
          PATH: ${{ env.PATH }}

      # Build the project
      - name: Build the project
        run: ~/.bun/bin/bun run build
        shell: bash
        env:
          BUN_INSTALL: ${{ env.BUN_INSTALL }}
          PATH: ${{ env.PATH }}

      # Determine the branch to deploy
      - name: Determine branch to deploy
        id: deploy-branch
        run: |
          if [[ ${{ env.IS_FASTDEV }} == 'true' ]]; then
            echo "branch=gh-pages-beta" >> $GITHUB_ENV
          else
            echo "branch=gh-pages" >> $GITHUB_ENV
