name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - '**/FASTDEV**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Bun
      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "PATH=$BUN_INSTALL/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      # Cache Bun dependencies
      - name: Bun Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build the project
      - name: Build the project
        run: bun run build

      # Determine the branch to deploy
      - name: Determine branch to deploy
        id: deploy-branch
        run: echo "::set-output name=branch::$(if echo $GITHUB_REF | grep -q 'FASTDEV'; then echo 'gh-pages-beta'; else echo 'gh-pages'; fi)"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: ${{ steps.deploy-branch.outputs.branch }}
